--
-- Name: app_configurations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.app_configurations (
    id bigint NOT NULL,
    code character varying(100) NOT NULL,
    global_value character varying(255),
    web_value character varying(255),
    mob_value character varying(255)
);


ALTER TABLE public.app_configurations OWNER TO postgres;

--
-- Name: app_configurations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.app_configurations ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.app_configurations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_customer; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.app_customer (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by bigint NOT NULL,
    modified_at timestamp(6) without time zone,
    modified_by bigint,
    address character varying(255),
    document_id bigint,
    email character varying(255),
    mobile character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    deleted boolean DEFAULT false NOT NULL,
    version bigint DEFAULT 0 NOT NULL
);


ALTER TABLE public.app_customer OWNER TO postgres;

--
-- Name: app_customer_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.app_customer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_customer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_direct_entry; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.app_direct_entry (
    id bigint NOT NULL,
    entry_date date NOT NULL,
    coa_id bigint NOT NULL,
    direction character varying(5) NOT NULL,
    amount numeric(15,2) NOT NULL,
    payment_account_id bigint NOT NULL,
    party_name character varying(150),
    reference_no character varying(100),
    description character varying(500),
    notes text,
    deleted boolean DEFAULT false NOT NULL,
    created_by bigint NOT NULL,
    created_at timestamp without time zone NOT NULL,
    modified_by bigint,
    modified_at timestamp without time zone,
    version bigint DEFAULT 0 NOT NULL
);


ALTER TABLE public.app_direct_entry OWNER TO postgres;

--
-- Name: app_direct_entry_aud; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.app_direct_entry_aud (
    amount numeric(38,2),
    entry_date date,
    revtype smallint,
    coa_id bigint,
    created_at timestamp(6) without time zone,
    created_by bigint,
    id bigint NOT NULL,
    modified_at timestamp(6) without time zone,
    modified_by bigint,
    payment_account_id bigint,
    rev bigint NOT NULL,
    description character varying(255),
    direction character varying(255),
    notes character varying(255),
    party_name character varying(255),
    reference_no character varying(255),
    CONSTRAINT app_direct_entry_aud_direction_check CHECK (((direction)::text = ANY ((ARRAY['IN'::character varying, 'OUT'::character varying])::text[])))
);


ALTER TABLE public.app_direct_entry_aud OWNER TO postgres;

--
-- Name: app_direct_entry_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.app_direct_entry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.app_direct_entry_id_seq OWNER TO postgres;

--
-- Name: app_direct_entry_id_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.app_direct_entry_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.app_direct_entry_id_seq1 OWNER TO postgres;

--
-- Name: app_direct_entry_id_seq1; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.app_direct_entry_id_seq1 OWNED BY public.app_direct_entry.id;


--
-- Name: app_document_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.app_document_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.app_document_id_seq OWNER TO postgres;

--
-- Name: app_document; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.app_document (
    id bigint DEFAULT nextval('public.app_document_id_seq'::regclass) NOT NULL,
    type character varying NOT NULL,
    total_docs integer,
    created_by bigint,
    created_at timestamp without time zone,
    modified_by bigint,
    modified_at timestamp without time zone,
    name character varying NOT NULL
);


ALTER TABLE public.app_document OWNER TO postgres;

--
-- Name: app_document_detail_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.app_document_detail_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.app_document_detail_id_seq OWNER TO postgres;

--
-- Name: app_document_detail; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.app_document_detail (
    id bigint DEFAULT nextval('public.app_document_detail_id_seq'::regclass) NOT NULL,
    document_id bigint NOT NULL,
    doc_name character varying NOT NULL,
    doc_type character varying NOT NULL,
    doc_url character varying,
    doc_data bytea,
    created_at timestamp without time zone,
    created_by bigint,
    modified_at timestamp without time zone,
    modified_by bigint
);


ALTER TABLE public.app_document_detail OWNER TO postgres;

--
-- Name: app_purchase_expense_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.app_purchase_expense_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.app_purchase_expense_id_seq OWNER TO postgres;

--
-- Name: app_expense; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.app_expense (
    id bigint DEFAULT nextval('public.app_purchase_expense_id_seq'::regclass) NOT NULL,
    purchase_order_id bigint,
    expense_account_id bigint NOT NULL,
    other_expense character varying(255),
    description character varying(255),
    amount numeric(38,2) NOT NULL,
    created_by bigint NOT NULL,
    created_at timestamp without time zone NOT NULL,
    modified_by bigint,
    modified_at timestamp without time zone,
    date date NOT NULL,
    deleted boolean DEFAULT false NOT NULL,
    payment_account_id bigint,
    version bigint DEFAULT 0 NOT NULL
);


ALTER TABLE public.app_expense OWNER TO postgres;

--
-- Name: app_expense_aud; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.app_expense_aud (
    amount numeric(38,2),
    date date,
    revtype smallint,
    created_at timestamp(6) without time zone,
    created_by bigint,
    expense_account_id bigint,
    id bigint NOT NULL,
    modified_at timestamp(6) without time zone,
    modified_by bigint,
    payment_account_id bigint,
    purchase_order_id bigint,
    rev bigint NOT NULL,
    description character varying(255),
    other_expense character varying(255)
);


ALTER TABLE public.app_expense_aud OWNER TO postgres;

--
-- Name: app_inventory_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.app_inventory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.app_inventory_id_seq OWNER TO postgres;

--
-- Name: app_inventory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.app_inventory (
    id bigint DEFAULT nextval('public.app_inventory_id_seq'::regclass) NOT NULL,
    purchase_order_detail_id bigint NOT NULL,
    product_id bigint NOT NULL,
    uin character varying(255) NOT NULL,
    warehouse_id bigint,
    landed_cost numeric(38,2),
    status character varying(255) NOT NULL,
    received_date timestamp without time zone,
    created_by bigint,
    created_at timestamp without time zone,
    modified_at timestamp without time zone,
    modified_by bigint,
    product_no character varying(255),
    source_sale_id bigint,
    deleted boolean NOT NULL,
    odometer bigint,
    make_year character varying(255),
    color_id bigint,
    version bigint DEFAULT 0 NOT NULL
);


ALTER TABLE public.app_inventory OWNER TO postgres;

--
-- Name: app_journal; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.app_journal (
    id bigint NOT NULL,
    journal_date date NOT NULL,
    reference_type character varying(50) NOT NULL,
    reference_id bigint NOT NULL,
    description character varying(500),
    status character varying(20) DEFAULT 'POSTED'::character varying NOT NULL,
    reversal_of_id bigint,
    created_by bigint NOT NULL,
    created_at timestamp without time zone NOT NULL,
    modified_by bigint,
    modified_at timestamp without time zone,
    version bigint DEFAULT 0 NOT NULL
);


ALTER TABLE public.app_journal OWNER TO postgres;

--
-- Name: app_journal_detail; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.app_journal_detail (
    id bigint NOT NULL,
    journal_id bigint NOT NULL,
    account_id bigint NOT NULL,
    debit_amount numeric(15,2) DEFAULT 0 NOT NULL,
    credit_amount numeric(15,2) DEFAULT 0 NOT NULL,
    description character varying(500),
    created_by bigint NOT NULL,
    created_at timestamp without time zone NOT NULL,
    modified_by bigint,
    modified_at timestamp without time zone,
    version bigint DEFAULT 0 NOT NULL,
    CONSTRAINT chk_jdetail_balance CHECK ((((debit_amount > (0)::numeric) AND (credit_amount = (0)::numeric)) OR ((credit_amount > (0)::numeric) AND (debit_amount = (0)::numeric))))
);


ALTER TABLE public.app_journal_detail OWNER TO postgres;

--
-- Name: app_journal_detail_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.app_journal_detail_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.app_journal_detail_id_seq OWNER TO postgres;

--
-- Name: app_journal_detail_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.app_journal_detail_id_seq OWNED BY public.app_journal_detail.id;


--
-- Name: app_journal_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.app_journal_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.app_journal_id_seq OWNER TO postgres;

--
-- Name: app_journal_id_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.app_journal_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.app_journal_id_seq1 OWNER TO postgres;

--
-- Name: app_journal_id_seq1; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.app_journal_id_seq1 OWNED BY public.app_journal.id;


--
-- Name: app_payment_account; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.app_payment_account (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    bank_name character varying(100),
    account_no character varying(50),
    ifsc_code character varying(20),
    account_type character varying(10) NOT NULL,
    opening_balance numeric(15,2) DEFAULT 0 NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_by bigint NOT NULL,
    created_at timestamp without time zone NOT NULL,
    modified_by bigint,
    modified_at timestamp without time zone,
    coa_id bigint,
    opening_date date,
    version bigint DEFAULT 0 NOT NULL
);


ALTER TABLE public.app_payment_account OWNER TO postgres;

--
-- Name: app_payment_account_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.app_payment_account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.app_payment_account_id_seq OWNER TO postgres;

--
-- Name: app_payment_account_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.app_payment_account_id_seq OWNED BY public.app_payment_account.id;


--
-- Name: app_product_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.app_product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.app_product_id_seq OWNER TO postgres;

--
-- Name: app_product; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.app_product (
    id bigint DEFAULT nextval('public.app_product_id_seq'::regclass) NOT NULL,
    sku character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    description character varying(255),
    category_id bigint NOT NULL,
    brand_id bigint NOT NULL,
    model_id bigint NOT NULL,
    varient_id bigint NOT NULL,
    created_at timestamp without time zone NOT NULL,
    created_by bigint NOT NULL,
    modified_at timestamp without time zone,
    modified_by bigint,
    document_id bigint,
    deleted boolean NOT NULL,
    segment_id bigint,
    fuel_type_id bigint,
    version bigint DEFAULT 0 NOT NULL,
    transmission_type_id bigint
);


ALTER TABLE public.app_product OWNER TO postgres;

--
-- Name: product_segment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.product_segment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.product_segment_id_seq OWNER TO postgres;

--
-- Name: app_product_segment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.app_product_segment (
    id bigint DEFAULT nextval('public.product_segment_id_seq'::regclass) NOT NULL,
    category_id bigint NOT NULL,
    code character varying(50) NOT NULL,
    description character varying NOT NULL,
    active boolean DEFAULT true NOT NULL,
    sort_order integer
);


ALTER TABLE public.app_product_segment OWNER TO postgres;

--
-- Name: app_purchase_order_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.app_purchase_order_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.app_purchase_order_id_seq OWNER TO postgres;

--
-- Name: app_purchase_order; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.app_purchase_order (
    id bigint DEFAULT nextval('public.app_purchase_order_id_seq'::regclass) NOT NULL,
    reference_no character varying(255) NOT NULL,
    vendor_id bigint NOT NULL,
    order_date date NOT NULL,
    delivered_date date,
    status_id bigint NOT NULL,
    total_amount numeric(38,2) NOT NULL,
    notes character varying(255),
    created_by bigint,
    created_at timestamp without time zone,
    modified_by bigint,
    modified_at timestamp without time zone,
    pickup_location character varying(255),
    pickup_staff_id bigint,
    deleted boolean NOT NULL,
    buyback_recorded_at date,
    version bigint DEFAULT 0 NOT NULL
);


ALTER TABLE public.app_purchase_order OWNER TO postgres;

--
-- Name: app_purchase_order_aud; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.app_purchase_order_aud (
    buyback_recorded_at date,
    delivered_date date,
    order_date date,
    revtype smallint,
    total_amount numeric(38,2),
    created_at timestamp(6) without time zone,
    created_by bigint,
    id bigint NOT NULL,
    modified_at timestamp(6) without time zone,
    modified_by bigint,
    pickup_staff_id bigint,
    rev bigint NOT NULL,
    status_id bigint,
    vendor_id bigint,
    notes character varying(255),
    pickup_location character varying(255),
    reference_no character varying(255)
);


ALTER TABLE public.app_purchase_order_aud OWNER TO postgres;

--
-- Name: app_purchase_order_detail_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.app_purchase_order_detail_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.app_purchase_order_detail_id_seq OWNER TO postgres;

--
-- Name: app_purchase_order_detail; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.app_purchase_order_detail (
    id bigint DEFAULT nextval('public.app_purchase_order_detail_id_seq'::regclass) NOT NULL,
    purchase_order_id bigint NOT NULL,
    product_id bigint NOT NULL,
    item_uid character varying(255),
    quantity double precision NOT NULL,
    unit_cost numeric(38,2) NOT NULL,
    discount numeric(38,2),
    discount_amount numeric(38,2),
    tax numeric(38,2),
    tax_amount numeric(38,2),
    product_no character varying(255),
    odometer character varying(255),
    ownership_serial_no character varying,
    deleted boolean DEFAULT false NOT NULL
);


ALTER TABLE public.app_purchase_order_detail OWNER TO postgres;

--
-- Name: app_purchase_payment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.app_purchase_payment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.app_purchase_payment_id_seq OWNER TO postgres;

--
-- Name: app_purchase_payment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.app_purchase_payment (
    id bigint DEFAULT nextval('public.app_purchase_payment_id_seq'::regclass) NOT NULL,
    purchase_order_id bigint NOT NULL,
    amount numeric NOT NULL,
    payment_date date NOT NULL,
    payment_method character varying(20) NOT NULL,
    account_id bigint,
    reference_no character varying(100),
    notes character varying(500),
    deleted boolean DEFAULT false,
    created_by bigint NOT NULL,
    created_at timestamp without time zone NOT NULL,
    modified_by bigint,
    modified_at timestamp without time zone,
    payment_account_id bigint,
    version bigint DEFAULT 0 NOT NULL
);


ALTER TABLE public.app_purchase_payment OWNER TO postgres;

--
-- Name: app_purchase_payment_aud; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.app_purchase_payment_aud (
    amount numeric(38,2),
    payment_date date,
    revtype smallint,
    created_at timestamp(6) without time zone,
    created_by bigint,
    id bigint NOT NULL,
    modified_at timestamp(6) without time zone,
    modified_by bigint,
    payment_account_id bigint,
    purchase_order_id bigint,
    rev bigint NOT NULL,
    notes character varying(255),
    payment_method character varying(255),
    reference_no character varying(255),
    CONSTRAINT app_purchase_payment_aud_payment_method_check CHECK (((payment_method)::text = ANY ((ARRAY['CASH'::character varying, 'BANK'::character varying, 'CHEQUE'::character varying])::text[])))
);


ALTER TABLE public.app_purchase_payment_aud OWNER TO postgres;

--
-- Name: app_purchase_return; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.app_purchase_return (
    id bigint NOT NULL,
    purchase_id bigint NOT NULL,
    inventory_id bigint NOT NULL,
    return_date date NOT NULL,
    reason character varying(500),
    notes text,
    inventory_landed_cost numeric(15,2) NOT NULL,
    return_amount numeric(15,2) NOT NULL,
    status character varying(20) NOT NULL,
    created_by bigint,
    created_at timestamp without time zone,
    modified_by bigint,
    modified_at timestamp without time zone,
    deleted boolean DEFAULT false,
    version bigint DEFAULT 0 NOT NULL,
    CONSTRAINT chk_pr_status_valid CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'COMPLETED'::character varying])::text[])))
);


ALTER TABLE public.app_purchase_return OWNER TO postgres;

--
-- Name: app_purchase_return_aud; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.app_purchase_return_aud (
    inventory_landed_cost numeric(38,2),
    return_amount numeric(38,2),
    return_date date,
    revtype smallint,
    created_at timestamp(6) without time zone,
    created_by bigint,
    id bigint NOT NULL,
    inventory_id bigint,
    modified_at timestamp(6) without time zone,
    modified_by bigint,
    purchase_id bigint,
    rev bigint NOT NULL,
    notes character varying(255),
    reason character varying(255),
    status character varying(255),
    CONSTRAINT app_purchase_return_aud_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'COMPLETED'::character varying])::text[])))
);


ALTER TABLE public.app_purchase_return_aud OWNER TO postgres;

--
-- Name: app_purchase_return_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.app_purchase_return_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.app_purchase_return_id_seq OWNER TO postgres;

--
-- Name: app_purchase_return_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.app_purchase_return_id_seq OWNED BY public.app_purchase_return.id;


--
-- Name: app_purchase_return_receipt; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.app_purchase_return_receipt (
    id bigint NOT NULL,
    purchase_return_id bigint NOT NULL,
    amount numeric(15,2) NOT NULL,
    payment_date date NOT NULL,
    payment_method character varying(50) NOT NULL,
    payment_account_id bigint NOT NULL,
    reference_no character varying(100),
    notes text,
    created_by bigint,
    created_at timestamp without time zone,
    modified_by bigint,
    modified_at timestamp without time zone,
    deleted boolean DEFAULT false,
    version bigint DEFAULT 0 NOT NULL
);


ALTER TABLE public.app_purchase_return_receipt OWNER TO postgres;

--
-- Name: app_purchase_return_receipt_aud; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.app_purchase_return_receipt_aud (
    amount numeric(38,2),
    payment_date date,
    revtype smallint,
    created_at timestamp(6) without time zone,
    created_by bigint,
    id bigint NOT NULL,
    modified_at timestamp(6) without time zone,
    modified_by bigint,
    payment_account_id bigint,
    purchase_return_id bigint,
    rev bigint NOT NULL,
    notes character varying(255),
    payment_method character varying(255),
    reference_no character varying(255),
    CONSTRAINT app_purchase_return_receipt_aud_payment_method_check CHECK (((payment_method)::text = ANY ((ARRAY['CASH'::character varying, 'BANK'::character varying, 'CHEQUE'::character varying])::text[])))
);


ALTER TABLE public.app_purchase_return_receipt_aud OWNER TO postgres;

--
-- Name: app_purchase_return_receipt_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.app_purchase_return_receipt_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.app_purchase_return_receipt_id_seq OWNER TO postgres;

--
-- Name: app_purchase_return_receipt_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.app_purchase_return_receipt_id_seq OWNED BY public.app_purchase_return_receipt.id;


--
-- Name: app_sale; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.app_sale (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by bigint NOT NULL,
    modified_at timestamp(6) without time zone,
    modified_by bigint,
    emi_amount numeric(38,2),
    exchange_amount numeric(38,2),
    finance_amount numeric(38,2),
    finance_company character varying(255),
    invoice_no character varying(255) NOT NULL,
    is_exchanged boolean,
    is_financed boolean,
    landed_cost_at_sale numeric(38,2),
    net_sale_amount numeric(38,2),
    payment_status character varying(255) NOT NULL,
    profit_amount numeric(38,2),
    sale_date date NOT NULL,
    sale_rate numeric(38,2) NOT NULL,
    deleted boolean NOT NULL,
    customer_id bigint NOT NULL,
    inventory_id bigint NOT NULL,
    status_id bigint NOT NULL,
    version bigint DEFAULT 0 NOT NULL,
    CONSTRAINT app_sale_payment_status_check CHECK (((payment_status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'DELETED'::character varying, 'AVAILABLE'::character varying, 'OUT_OF_STOCK'::character varying, 'PENDING'::character varying, 'RECIEVED'::character varying, 'SOLD'::character varying, 'CANCELLED'::character varying, 'COMPLETED'::character varying, 'PAID'::character varying, 'PARTIAL'::character varying, 'FINANCE_PENDING'::character varying, 'REFUND'::character varying])::text[])))
);


ALTER TABLE public.app_sale OWNER TO postgres;

--
-- Name: COLUMN app_sale.deleted; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.app_sale.deleted IS 'Soft-delete indicator';


--
-- Name: app_sale_amount_split; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.app_sale_amount_split (
    id bigint NOT NULL,
    sale_id bigint NOT NULL,
    type_id bigint NOT NULL,
    amount numeric(19,2) NOT NULL,
    created_at timestamp without time zone,
    created_by bigint,
    modified_at timestamp without time zone,
    modified_by bigint,
    deleted boolean DEFAULT false,
    version bigint DEFAULT 0 NOT NULL
);


ALTER TABLE public.app_sale_amount_split OWNER TO postgres;

--
-- Name: app_sale_amount_split_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.app_sale_amount_split_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.app_sale_amount_split_id_seq OWNER TO postgres;

--
-- Name: app_sale_amount_split_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.app_sale_amount_split_id_seq OWNED BY public.app_sale_amount_split.id;


--
-- Name: app_sale_aud; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.app_sale_aud (
    emi_amount numeric(38,2),
    exchange_amount numeric(38,2),
    finance_amount numeric(38,2),
    is_exchanged boolean,
    is_financed boolean,
    landed_cost_at_sale numeric(38,2),
    net_sale_amount numeric(38,2),
    profit_amount numeric(38,2),
    revtype smallint,
    sale_date date,
    sale_rate numeric(38,2),
    created_at timestamp(6) without time zone,
    created_by bigint,
    customer_id bigint,
    id bigint NOT NULL,
    inventory_id bigint,
    modified_at timestamp(6) without time zone,
    modified_by bigint,
    rev bigint NOT NULL,
    status_id bigint,
    finance_company character varying(255),
    invoice_no character varying(255),
    payment_status character varying(255),
    CONSTRAINT app_sale_aud_payment_status_check CHECK (((payment_status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'DELETED'::character varying, 'AVAILABLE'::character varying, 'OUT_OF_STOCK'::character varying, 'PENDING_DELIVERY'::character varying, 'RETURNED_TO_VENDOR'::character varying, 'PENDING'::character varying, 'RECIEVED'::character varying, 'SOLD'::character varying, 'CANCELLED'::character varying, 'COMPLETED'::character varying, 'PAID'::character varying, 'PARTIAL'::character varying, 'FINANCE_PENDING'::character varying, 'REFUND'::character varying, 'RETURNED'::character varying])::text[])))
);


ALTER TABLE public.app_sale_aud OWNER TO postgres;

--
-- Name: app_sale_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.app_sale ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_sale_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_sale_payment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.app_sale_payment (
    id bigint NOT NULL,
    sale_id bigint NOT NULL,
    amount numeric(19,2) NOT NULL,
    payment_date date NOT NULL,
    payment_method character varying(20) NOT NULL,
    payer_type character varying(20) NOT NULL,
    payment_account_id bigint,
    reference_no character varying(100),
    notes character varying(500),
    deleted boolean DEFAULT false,
    created_by bigint NOT NULL,
    created_at timestamp without time zone NOT NULL,
    modified_by bigint,
    modified_at timestamp without time zone,
    version bigint DEFAULT 0 NOT NULL
);


ALTER TABLE public.app_sale_payment OWNER TO postgres;

--
-- Name: app_sale_payment_aud; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.app_sale_payment_aud (
    amount numeric(38,2),
    payment_date date,
    revtype smallint,
    created_at timestamp(6) without time zone,
    created_by bigint,
    id bigint NOT NULL,
    modified_at timestamp(6) without time zone,
    modified_by bigint,
    payment_account_id bigint,
    rev bigint NOT NULL,
    sale_id bigint,
    notes character varying(255),
    payer_type character varying(255),
    payment_method character varying(255),
    reference_no character varying(255),
    CONSTRAINT app_sale_payment_aud_payer_type_check CHECK (((payer_type)::text = ANY ((ARRAY['CUSTOMER'::character varying, 'FINANCE'::character varying])::text[]))),
    CONSTRAINT app_sale_payment_aud_payment_method_check CHECK (((payment_method)::text = ANY ((ARRAY['CASH'::character varying, 'BANK'::character varying, 'CHEQUE'::character varying])::text[])))
);


ALTER TABLE public.app_sale_payment_aud OWNER TO postgres;

--
-- Name: app_sale_payment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.app_sale_payment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.app_sale_payment_id_seq OWNER TO postgres;

--
-- Name: app_sale_payment_id_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.app_sale_payment_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.app_sale_payment_id_seq1 OWNER TO postgres;

--
-- Name: app_sale_payment_id_seq1; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.app_sale_payment_id_seq1 OWNED BY public.app_sale_payment.id;


--
-- Name: app_sale_refund_payment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.app_sale_refund_payment (
    id bigint NOT NULL,
    sale_return_id bigint NOT NULL,
    amount numeric(15,2) NOT NULL,
    payment_date date NOT NULL,
    payment_method character varying(50) NOT NULL,
    payment_account_id bigint NOT NULL,
    reference_no character varying(100),
    notes text,
    created_by bigint,
    created_at timestamp without time zone,
    modified_by bigint,
    modified_at timestamp without time zone,
    deleted boolean DEFAULT false,
    version bigint DEFAULT 0 NOT NULL
);


ALTER TABLE public.app_sale_refund_payment OWNER TO postgres;

--
-- Name: app_sale_refund_payment_aud; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.app_sale_refund_payment_aud (
    amount numeric(38,2),
    payment_date date,
    revtype smallint,
    created_at timestamp(6) without time zone,
    created_by bigint,
    id bigint NOT NULL,
    modified_at timestamp(6) without time zone,
    modified_by bigint,
    payment_account_id bigint,
    rev bigint NOT NULL,
    sale_return_id bigint,
    notes character varying(255),
    payment_method character varying(255),
    reference_no character varying(255),
    CONSTRAINT app_sale_refund_payment_aud_payment_method_check CHECK (((payment_method)::text = ANY ((ARRAY['CASH'::character varying, 'BANK'::character varying, 'CHEQUE'::character varying])::text[])))
);


ALTER TABLE public.app_sale_refund_payment_aud OWNER TO postgres;

--
-- Name: app_sale_refund_payment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.app_sale_refund_payment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.app_sale_refund_payment_id_seq OWNER TO postgres;

--
-- Name: app_sale_refund_payment_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.app_sale_refund_payment_id_seq OWNED BY public.app_sale_refund_payment.id;


--
-- Name: app_sale_return; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.app_sale_return (
    id bigint NOT NULL,
    sale_id bigint NOT NULL,
    return_date date NOT NULL,
    reason character varying(500),
    notes text,
    customer_paid_amount numeric(15,2) NOT NULL,
    exchange_handling character varying(20) NOT NULL,
    exchange_buyback_amount numeric(15,2),
    sold_vehicle_deduction_amount numeric(15,2) DEFAULT 0 NOT NULL,
    exchange_vehicle_deduction_amount numeric(15,2) DEFAULT 0 NOT NULL,
    refund_amount numeric(15,2) NOT NULL,
    status character varying(20) NOT NULL,
    created_by bigint,
    created_at timestamp without time zone,
    modified_by bigint,
    modified_at timestamp without time zone,
    deleted boolean DEFAULT false,
    version bigint DEFAULT 0 NOT NULL,
    CONSTRAINT chk_buyback_only_when_keep CHECK (((((exchange_handling)::text = 'KEEP_AND_BUYBACK'::text) AND (exchange_buyback_amount IS NOT NULL)) OR (((exchange_handling)::text <> 'KEEP_AND_BUYBACK'::text) AND (exchange_buyback_amount IS NULL)))),
    CONSTRAINT chk_exchange_handling_valid CHECK (((exchange_handling)::text = ANY ((ARRAY['NONE'::character varying, 'RETURN_TO_BUYER'::character varying, 'KEEP_AND_BUYBACK'::character varying])::text[]))),
    CONSTRAINT chk_status_valid CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'COMPLETED'::character varying])::text[])))
);


ALTER TABLE public.app_sale_return OWNER TO postgres;

--
-- Name: app_sale_return_aud; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.app_sale_return_aud (
    customer_paid_amount numeric(38,2),
    exchange_buyback_amount numeric(38,2),
    exchange_vehicle_deduction_amount numeric(38,2),
    refund_amount numeric(38,2),
    return_date date,
    revtype smallint,
    sold_vehicle_deduction_amount numeric(38,2),
    created_at timestamp(6) without time zone,
    created_by bigint,
    id bigint NOT NULL,
    modified_at timestamp(6) without time zone,
    modified_by bigint,
    rev bigint NOT NULL,
    sale_id bigint,
    exchange_handling character varying(255),
    notes character varying(255),
    reason character varying(255),
    status character varying(255),
    CONSTRAINT app_sale_return_aud_exchange_handling_check CHECK (((exchange_handling)::text = ANY ((ARRAY['NONE'::character varying, 'RETURN_TO_BUYER'::character varying, 'KEEP_AND_BUYBACK'::character varying])::text[]))),
    CONSTRAINT app_sale_return_aud_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'COMPLETED'::character varying])::text[])))
);


ALTER TABLE public.app_sale_return_aud OWNER TO postgres;

--
-- Name: app_sale_return_deduction; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.app_sale_return_deduction (
    id bigint NOT NULL,
    sale_return_id bigint NOT NULL,
    vehicle_context character varying(20) NOT NULL,
    expense_id bigint,
    description character varying(255) NOT NULL,
    amount numeric(15,2) NOT NULL,
    created_by bigint,
    created_at timestamp without time zone,
    modified_by bigint,
    modified_at timestamp without time zone,
    version bigint DEFAULT 0 NOT NULL,
    CONSTRAINT chk_ded_context_valid CHECK (((vehicle_context)::text = ANY ((ARRAY['SOLD'::character varying, 'EXCHANGE'::character varying])::text[])))
);


ALTER TABLE public.app_sale_return_deduction OWNER TO postgres;

--
-- Name: app_sale_return_deduction_aud; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.app_sale_return_deduction_aud (
    amount numeric(38,2),
    revtype smallint,
    created_at timestamp(6) without time zone,
    created_by bigint,
    expense_id bigint,
    id bigint NOT NULL,
    modified_at timestamp(6) without time zone,
    modified_by bigint,
    rev bigint NOT NULL,
    sale_return_id bigint,
    description character varying(255),
    vehicle_context character varying(255),
    CONSTRAINT app_sale_return_deduction_aud_vehicle_context_check CHECK (((vehicle_context)::text = ANY ((ARRAY['SOLD'::character varying, 'EXCHANGE'::character varying])::text[])))
);


ALTER TABLE public.app_sale_return_deduction_aud OWNER TO postgres;

--
-- Name: app_sale_return_deduction_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.app_sale_return_deduction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.app_sale_return_deduction_id_seq OWNER TO postgres;

--
-- Name: app_sale_return_deduction_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.app_sale_return_deduction_id_seq OWNED BY public.app_sale_return_deduction.id;


--
-- Name: app_sale_return_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.app_sale_return_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.app_sale_return_id_seq OWNER TO postgres;

--
-- Name: app_sale_return_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.app_sale_return_id_seq OWNED BY public.app_sale_return.id;


--
-- Name: app_transaction; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.app_transaction (
    id bigint NOT NULL,
    transaction_date date NOT NULL,
    type character varying(30) NOT NULL,
    reference_type character varying(30) NOT NULL,
    reference_id bigint NOT NULL,
    payment_account_id bigint,
    amount numeric(15,2) NOT NULL,
    direction character varying(5) NOT NULL,
    description character varying(255),
    notes text,
    reversal_of_id bigint,
    created_by bigint NOT NULL,
    created_at timestamp without time zone NOT NULL,
    modified_by bigint,
    modified_at timestamp without time zone,
    reconciled boolean DEFAULT false NOT NULL,
    reconciled_at date,
    version bigint DEFAULT 0 NOT NULL
);


ALTER TABLE public.app_transaction OWNER TO postgres;

--
-- Name: app_transaction_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.app_transaction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.app_transaction_id_seq OWNER TO postgres;

--
-- Name: app_transaction_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.app_transaction_id_seq OWNED BY public.app_transaction.id;


--
-- Name: app_vendor_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.app_vendor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.app_vendor_id_seq OWNER TO postgres;

--
-- Name: app_vendor; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.app_vendor (
    id bigint DEFAULT nextval('public.app_vendor_id_seq'::regclass) NOT NULL,
    name character varying(255) NOT NULL,
    address character varying(255),
    mobile character varying(255) NOT NULL,
    email character varying(255),
    document_id bigint,
    created_at timestamp without time zone,
    created_by bigint,
    modified_at timestamp without time zone,
    modified_by bigint,
    deleted boolean DEFAULT false NOT NULL,
    version bigint DEFAULT 0 NOT NULL
);


ALTER TABLE public.app_vendor OWNER TO postgres;

--
-- Name: fnd_brand_model_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.fnd_brand_model_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.fnd_brand_model_id_seq OWNER TO postgres;

--
-- Name: fnd_brand_model; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.fnd_brand_model (
    id bigint DEFAULT nextval('public.fnd_brand_model_id_seq'::regclass) NOT NULL,
    brand_id bigint NOT NULL,
    code character varying(255) NOT NULL,
    description character varying(255) NOT NULL,
    sort_order integer DEFAULT 0,
    active boolean DEFAULT true NOT NULL
);


ALTER TABLE public.fnd_brand_model OWNER TO postgres;

--
-- Name: fnd_chart_of_accounts_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.fnd_chart_of_accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.fnd_chart_of_accounts_id_seq OWNER TO postgres;

--
-- Name: fnd_chart_of_accounts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.fnd_chart_of_accounts (
    id bigint DEFAULT nextval('public.fnd_chart_of_accounts_id_seq'::regclass) NOT NULL,
    code character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    description character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    is_control_account boolean NOT NULL,
    created_at timestamp without time zone,
    created_by bigint,
    modified_at timestamp without time zone,
    modified_by bigint,
    label character varying(255) NOT NULL,
    deleted boolean DEFAULT false,
    is_direct_postable boolean DEFAULT false NOT NULL,
    system_role character varying(50),
    version bigint DEFAULT 0 NOT NULL
);


ALTER TABLE public.fnd_chart_of_accounts OWNER TO postgres;

--
-- Name: fnd_lookup_master_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.fnd_lookup_master_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.fnd_lookup_master_id_seq OWNER TO postgres;

--
-- Name: fnd_lookup_master; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.fnd_lookup_master (
    id bigint DEFAULT nextval('public.fnd_lookup_master_id_seq'::regclass) NOT NULL,
    code character varying(255) NOT NULL,
    description character varying(255) NOT NULL,
    sort_order integer DEFAULT 0,
    enabled boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone,
    created_by bigint,
    modified_at timestamp without time zone,
    modified_by bigint,
    type character varying(255) NOT NULL,
    deleted boolean DEFAULT false,
    offset_coa_id bigint,
    version bigint DEFAULT 0 NOT NULL
);


ALTER TABLE public.fnd_lookup_master OWNER TO postgres;

--
-- Name: fnd_model_varient_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.fnd_model_varient_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.fnd_model_varient_id_seq OWNER TO postgres;

--
-- Name: fnd_model_varient; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.fnd_model_varient (
    id bigint DEFAULT nextval('public.fnd_model_varient_id_seq'::regclass) NOT NULL,
    model_id bigint NOT NULL,
    code character varying(255) NOT NULL,
    description character varying(255) NOT NULL,
    sort_order integer DEFAULT 0,
    active boolean DEFAULT true NOT NULL,
    type character varying(255)
);


ALTER TABLE public.fnd_model_varient OWNER TO postgres;

--
-- Name: fnd_module; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.fnd_module (
    id bigint NOT NULL,
    code character varying(255) NOT NULL,
    description character varying(255) NOT NULL,
    sort_order integer DEFAULT 0,
    active boolean DEFAULT true NOT NULL
);


ALTER TABLE public.fnd_module OWNER TO postgres;

--
-- Name: fnd_module_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.fnd_module ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.fnd_module_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: fnd_product_brand_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.fnd_product_brand_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.fnd_product_brand_id_seq OWNER TO postgres;

--
-- Name: fnd_product_brand; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.fnd_product_brand (
    id bigint DEFAULT nextval('public.fnd_product_brand_id_seq'::regclass) NOT NULL,
    category_id bigint NOT NULL,
    code character varying(255) NOT NULL,
    description character varying(255) NOT NULL,
    sort_order integer DEFAULT 0,
    active boolean DEFAULT true NOT NULL
);


ALTER TABLE public.fnd_product_brand OWNER TO postgres;

--
-- Name: fnd_product_category_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.fnd_product_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.fnd_product_category_id_seq OWNER TO postgres;

--
-- Name: fnd_product_category; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.fnd_product_category (
    id bigint DEFAULT nextval('public.fnd_product_category_id_seq'::regclass) NOT NULL,
    code character varying(255) NOT NULL,
    description character varying(255) NOT NULL,
    sort_order integer,
    active boolean DEFAULT true NOT NULL,
    expense_lock_enabled boolean DEFAULT false NOT NULL,
    expense_lock_window character varying(10)
);


ALTER TABLE public.fnd_product_category OWNER TO postgres;

--
-- Name: fnd_product_segment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.fnd_product_segment (
    id bigint NOT NULL,
    active boolean,
    code character varying(255) NOT NULL,
    description character varying(255) NOT NULL,
    sort_order integer,
    category_id bigint NOT NULL
);


ALTER TABLE public.fnd_product_segment OWNER TO postgres;

--
-- Name: fnd_product_segment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.fnd_product_segment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fnd_product_segment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: fnd_resource; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.fnd_resource (
    id bigint NOT NULL,
    module_id bigint NOT NULL,
    code character varying(255) NOT NULL,
    description character varying(255) NOT NULL,
    sort_order integer DEFAULT 0,
    active boolean DEFAULT true NOT NULL
);


ALTER TABLE public.fnd_resource OWNER TO postgres;

--
-- Name: fnd_resource_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.fnd_resource ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.fnd_resource_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: fnd_role; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.fnd_role (
    id bigint NOT NULL,
    code character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    description character varying(255),
    is_system boolean DEFAULT false NOT NULL,
    deleted boolean DEFAULT false NOT NULL,
    created_by bigint,
    created_at timestamp without time zone NOT NULL,
    modified_by bigint,
    modified_at timestamp without time zone,
    version bigint DEFAULT 0 NOT NULL
);


ALTER TABLE public.fnd_role OWNER TO postgres;

--
-- Name: fnd_role_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.fnd_role ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.fnd_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: fnd_role_privilege; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.fnd_role_privilege (
    id bigint NOT NULL,
    role_id bigint NOT NULL,
    resource_id bigint NOT NULL,
    privilege character varying(20) NOT NULL
);


ALTER TABLE public.fnd_role_privilege OWNER TO postgres;

--
-- Name: fnd_role_privilege_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.fnd_role_privilege ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.fnd_role_privilege_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inf_warehouse_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.inf_warehouse_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.inf_warehouse_id_seq OWNER TO postgres;

--
-- Name: inf_warehouse; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.inf_warehouse (
    id bigint DEFAULT nextval('public.inf_warehouse_id_seq'::regclass) NOT NULL,
    code character varying(50) NOT NULL,
    name character varying NOT NULL,
    address character varying,
    location text
);


ALTER TABLE public.inf_warehouse OWNER TO postgres;

--
-- Name: po_ref_no_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.po_ref_no_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.po_ref_no_seq OWNER TO postgres;

--
-- Name: revinfo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.revinfo (
    rev bigint NOT NULL,
    rev_timestamp bigint,
    user_id bigint
);


ALTER TABLE public.revinfo OWNER TO postgres;

--
-- Name: revinfo_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.revinfo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.revinfo_seq OWNER TO postgres;

--
-- Name: so_ref_no_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.so_ref_no_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.so_ref_no_seq OWNER TO postgres;

--
-- Name: user_profile_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.user_profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.user_profile_id_seq OWNER TO postgres;

--
-- Name: user_profile; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_profile (
    id bigint DEFAULT nextval('public.user_profile_id_seq'::regclass) NOT NULL,
    username character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    last_login_at timestamp without time zone,
    created_by bigint,
    created_at timestamp without time zone,
    modified_by bigint,
    modified_at timestamp without time zone,
    profile_photo_id bigint,
    deleted boolean DEFAULT false,
    role character varying,
    name character varying,
    designation character varying
);


ALTER TABLE public.user_profile OWNER TO postgres;

--
-- Name: user_refresh_token; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_refresh_token (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    token_hash character varying(255) NOT NULL,
    parent_id bigint,
    revoked boolean DEFAULT false NOT NULL,
    revoked_at timestamp without time zone,
    expires_at timestamp without time zone NOT NULL,
    created_at timestamp without time zone NOT NULL,
    session_id character varying(36)
);


ALTER TABLE public.user_refresh_token OWNER TO postgres;

--
-- Name: user_refresh_token_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_refresh_token ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.user_refresh_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_role; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_role (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    role_id bigint NOT NULL
);


ALTER TABLE public.user_role OWNER TO postgres;

--
-- Name: user_role_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_role ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.user_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_session (
    id bigint NOT NULL,
    session_id character varying(36) NOT NULL,
    user_id bigint NOT NULL,
    status character varying(20) NOT NULL,
    login_at timestamp without time zone NOT NULL,
    ended_at timestamp without time zone
);


ALTER TABLE public.user_session OWNER TO postgres;

--
-- Name: user_session_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_session ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.user_session_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: app_direct_entry id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_direct_entry ALTER COLUMN id SET DEFAULT nextval('public.app_direct_entry_id_seq1'::regclass);


--
-- Name: app_journal id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_journal ALTER COLUMN id SET DEFAULT nextval('public.app_journal_id_seq1'::regclass);


--
-- Name: app_journal_detail id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_journal_detail ALTER COLUMN id SET DEFAULT nextval('public.app_journal_detail_id_seq'::regclass);


--
-- Name: app_payment_account id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_payment_account ALTER COLUMN id SET DEFAULT nextval('public.app_payment_account_id_seq'::regclass);


--
-- Name: app_purchase_return id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_purchase_return ALTER COLUMN id SET DEFAULT nextval('public.app_purchase_return_id_seq'::regclass);


--
-- Name: app_purchase_return_receipt id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_purchase_return_receipt ALTER COLUMN id SET DEFAULT nextval('public.app_purchase_return_receipt_id_seq'::regclass);


--
-- Name: app_sale_amount_split id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_sale_amount_split ALTER COLUMN id SET DEFAULT nextval('public.app_sale_amount_split_id_seq'::regclass);


--
-- Name: app_sale_payment id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_sale_payment ALTER COLUMN id SET DEFAULT nextval('public.app_sale_payment_id_seq1'::regclass);


--
-- Name: app_sale_refund_payment id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_sale_refund_payment ALTER COLUMN id SET DEFAULT nextval('public.app_sale_refund_payment_id_seq'::regclass);


--
-- Name: app_sale_return id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_sale_return ALTER COLUMN id SET DEFAULT nextval('public.app_sale_return_id_seq'::regclass);


--
-- Name: app_sale_return_deduction id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_sale_return_deduction ALTER COLUMN id SET DEFAULT nextval('public.app_sale_return_deduction_id_seq'::regclass);


--
-- Name: app_transaction id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_transaction ALTER COLUMN id SET DEFAULT nextval('public.app_transaction_id_seq'::regclass);


--
-- Name: app_configurations app_configurations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_configurations
    ADD CONSTRAINT app_configurations_pkey PRIMARY KEY (id);


--
-- Name: app_customer app_customer_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_customer
    ADD CONSTRAINT app_customer_pkey PRIMARY KEY (id);


--
-- Name: app_direct_entry_aud app_direct_entry_aud_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_direct_entry_aud
    ADD CONSTRAINT app_direct_entry_aud_pkey PRIMARY KEY (id, rev);


--
-- Name: app_direct_entry app_direct_entry_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_direct_entry
    ADD CONSTRAINT app_direct_entry_pkey PRIMARY KEY (id);


--
-- Name: app_document_detail app_document_detail_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_document_detail
    ADD CONSTRAINT app_document_detail_pkey PRIMARY KEY (id);


--
-- Name: app_document app_document_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_document
    ADD CONSTRAINT app_document_pkey PRIMARY KEY (id);


--
-- Name: app_expense_aud app_expense_aud_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_expense_aud
    ADD CONSTRAINT app_expense_aud_pkey PRIMARY KEY (id, rev);


--
-- Name: app_inventory app_inventory_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_inventory
    ADD CONSTRAINT app_inventory_pkey PRIMARY KEY (id);


--
-- Name: app_journal_detail app_journal_detail_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_journal_detail
    ADD CONSTRAINT app_journal_detail_pkey PRIMARY KEY (id);


--
-- Name: app_journal app_journal_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_journal
    ADD CONSTRAINT app_journal_pkey PRIMARY KEY (id);


--
-- Name: app_payment_account app_payment_account_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_payment_account
    ADD CONSTRAINT app_payment_account_pkey PRIMARY KEY (id);


--
-- Name: app_product app_product_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_product
    ADD CONSTRAINT app_product_pkey PRIMARY KEY (id);


--
-- Name: app_product_segment app_product_segment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_product_segment
    ADD CONSTRAINT app_product_segment_pkey PRIMARY KEY (id);


--
-- Name: app_expense app_purchase_expense_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_expense
    ADD CONSTRAINT app_purchase_expense_pkey PRIMARY KEY (id);


--
-- Name: app_purchase_order_aud app_purchase_order_aud_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_purchase_order_aud
    ADD CONSTRAINT app_purchase_order_aud_pkey PRIMARY KEY (id, rev);


--
-- Name: app_purchase_order_detail app_purchase_order_detail_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_purchase_order_detail
    ADD CONSTRAINT app_purchase_order_detail_pkey PRIMARY KEY (id);


--
-- Name: app_purchase_order app_purchase_order_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_purchase_order
    ADD CONSTRAINT app_purchase_order_pkey PRIMARY KEY (id);


--
-- Name: app_purchase_payment_aud app_purchase_payment_aud_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_purchase_payment_aud
    ADD CONSTRAINT app_purchase_payment_aud_pkey PRIMARY KEY (id, rev);


--
-- Name: app_purchase_payment app_purchase_payment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_purchase_payment
    ADD CONSTRAINT app_purchase_payment_pkey PRIMARY KEY (id);


--
-- Name: app_purchase_return_aud app_purchase_return_aud_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_purchase_return_aud
    ADD CONSTRAINT app_purchase_return_aud_pkey PRIMARY KEY (id, rev);


--
-- Name: app_purchase_return app_purchase_return_inventory_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_purchase_return
    ADD CONSTRAINT app_purchase_return_inventory_id_key UNIQUE (inventory_id);


--
-- Name: app_purchase_return app_purchase_return_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_purchase_return
    ADD CONSTRAINT app_purchase_return_pkey PRIMARY KEY (id);


--
-- Name: app_purchase_return_receipt_aud app_purchase_return_receipt_aud_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_purchase_return_receipt_aud
    ADD CONSTRAINT app_purchase_return_receipt_aud_pkey PRIMARY KEY (id, rev);


--
-- Name: app_purchase_return_receipt app_purchase_return_receipt_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_purchase_return_receipt
    ADD CONSTRAINT app_purchase_return_receipt_pkey PRIMARY KEY (id);


--
-- Name: app_sale_amount_split app_sale_amount_split_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_sale_amount_split
    ADD CONSTRAINT app_sale_amount_split_pkey PRIMARY KEY (id);


--
-- Name: app_sale_aud app_sale_aud_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_sale_aud
    ADD CONSTRAINT app_sale_aud_pkey PRIMARY KEY (id, rev);


--
-- Name: app_sale_payment_aud app_sale_payment_aud_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_sale_payment_aud
    ADD CONSTRAINT app_sale_payment_aud_pkey PRIMARY KEY (id, rev);


--
-- Name: app_sale_payment app_sale_payment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_sale_payment
    ADD CONSTRAINT app_sale_payment_pkey PRIMARY KEY (id);


--
-- Name: app_sale app_sale_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_sale
    ADD CONSTRAINT app_sale_pkey PRIMARY KEY (id);


--
-- Name: app_sale_refund_payment_aud app_sale_refund_payment_aud_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_sale_refund_payment_aud
    ADD CONSTRAINT app_sale_refund_payment_aud_pkey PRIMARY KEY (id, rev);


--
-- Name: app_sale_refund_payment app_sale_refund_payment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_sale_refund_payment
    ADD CONSTRAINT app_sale_refund_payment_pkey PRIMARY KEY (id);


--
-- Name: app_sale_return_aud app_sale_return_aud_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_sale_return_aud
    ADD CONSTRAINT app_sale_return_aud_pkey PRIMARY KEY (id, rev);


--
-- Name: app_sale_return_deduction_aud app_sale_return_deduction_aud_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_sale_return_deduction_aud
    ADD CONSTRAINT app_sale_return_deduction_aud_pkey PRIMARY KEY (id, rev);


--
-- Name: app_sale_return_deduction app_sale_return_deduction_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_sale_return_deduction
    ADD CONSTRAINT app_sale_return_deduction_pkey PRIMARY KEY (id);


--
-- Name: app_sale_return app_sale_return_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_sale_return
    ADD CONSTRAINT app_sale_return_pkey PRIMARY KEY (id);


--
-- Name: app_sale_return app_sale_return_sale_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_sale_return
    ADD CONSTRAINT app_sale_return_sale_id_key UNIQUE (sale_id);


--
-- Name: app_transaction app_transaction_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_transaction
    ADD CONSTRAINT app_transaction_pkey PRIMARY KEY (id);


--
-- Name: app_vendor app_vendor_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_vendor
    ADD CONSTRAINT app_vendor_pkey PRIMARY KEY (id);


--
-- Name: fnd_product_brand brand_uk1; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fnd_product_brand
    ADD CONSTRAINT brand_uk1 UNIQUE (category_id, code);


--
-- Name: fnd_brand_model brand_uk2; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fnd_brand_model
    ADD CONSTRAINT brand_uk2 UNIQUE (brand_id, code);


--
-- Name: fnd_product_category category_uk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fnd_product_category
    ADD CONSTRAINT category_uk UNIQUE (code);


--
-- Name: fnd_brand_model fnd_brand_model_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fnd_brand_model
    ADD CONSTRAINT fnd_brand_model_pkey PRIMARY KEY (id);


--
-- Name: fnd_chart_of_accounts fnd_char_of_accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fnd_chart_of_accounts
    ADD CONSTRAINT fnd_char_of_accounts_pkey PRIMARY KEY (id);


--
-- Name: fnd_lookup_master fnd_lookup_master_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fnd_lookup_master
    ADD CONSTRAINT fnd_lookup_master_pkey PRIMARY KEY (id);


--
-- Name: fnd_model_varient fnd_model_varient_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fnd_model_varient
    ADD CONSTRAINT fnd_model_varient_pkey PRIMARY KEY (id);


--
-- Name: fnd_module fnd_module_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fnd_module
    ADD CONSTRAINT fnd_module_code_key UNIQUE (code);


--
-- Name: fnd_module fnd_module_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fnd_module
    ADD CONSTRAINT fnd_module_pkey PRIMARY KEY (id);


--
-- Name: fnd_product_brand fnd_product_brand_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fnd_product_brand
    ADD CONSTRAINT fnd_product_brand_pkey PRIMARY KEY (id);


--
-- Name: fnd_product_category fnd_product_category_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fnd_product_category
    ADD CONSTRAINT fnd_product_category_pkey PRIMARY KEY (id);


--
-- Name: fnd_product_segment fnd_product_segment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fnd_product_segment
    ADD CONSTRAINT fnd_product_segment_pkey PRIMARY KEY (id);


--
-- Name: fnd_resource fnd_resource_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fnd_resource
    ADD CONSTRAINT fnd_resource_code_key UNIQUE (code);


--
-- Name: fnd_resource fnd_resource_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fnd_resource
    ADD CONSTRAINT fnd_resource_pkey PRIMARY KEY (id);


--
-- Name: fnd_role fnd_role_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fnd_role
    ADD CONSTRAINT fnd_role_code_key UNIQUE (code);


--
-- Name: fnd_role fnd_role_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fnd_role
    ADD CONSTRAINT fnd_role_pkey PRIMARY KEY (id);


--
-- Name: fnd_role_privilege fnd_role_privilege_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fnd_role_privilege
    ADD CONSTRAINT fnd_role_privilege_pkey PRIMARY KEY (id);


--
-- Name: fnd_role_privilege fnd_role_privilege_role_id_resource_id_privilege_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fnd_role_privilege
    ADD CONSTRAINT fnd_role_privilege_role_id_resource_id_privilege_key UNIQUE (role_id, resource_id, privilege);


--
-- Name: inf_warehouse inf_warehouse_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inf_warehouse
    ADD CONSTRAINT inf_warehouse_pkey PRIMARY KEY (id);


--
-- Name: app_vendor mobile_uk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_vendor
    ADD CONSTRAINT mobile_uk UNIQUE (mobile);


--
-- Name: app_product product_uk1; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_product
    ADD CONSTRAINT product_uk1 UNIQUE (sku);


--
-- Name: app_purchase_order_detail purchase_detail_uk1; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_purchase_order_detail
    ADD CONSTRAINT purchase_detail_uk1 UNIQUE (purchase_order_id, product_id);


--
-- Name: app_purchase_order_detail purchase_detail_uk2; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_purchase_order_detail
    ADD CONSTRAINT purchase_detail_uk2 UNIQUE (product_id, item_uid);


--
-- Name: revinfo revinfo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.revinfo
    ADD CONSTRAINT revinfo_pkey PRIMARY KEY (rev);


--
-- Name: app_sale uk8f8cd9ubu8iqrbtngbquvfvgv; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_sale
    ADD CONSTRAINT uk8f8cd9ubu8iqrbtngbquvfvgv UNIQUE (invoice_no);


--
-- Name: app_configurations uk_app_configurations_code; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_configurations
    ADD CONSTRAINT uk_app_configurations_code UNIQUE (code);


--
-- Name: user_session uk_user_session_session_id; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_session
    ADD CONSTRAINT uk_user_session_session_id UNIQUE (session_id);


--
-- Name: user_profile user_profile_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_profile
    ADD CONSTRAINT user_profile_pkey PRIMARY KEY (id);


--
-- Name: user_refresh_token user_refresh_token_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_refresh_token
    ADD CONSTRAINT user_refresh_token_pkey PRIMARY KEY (id);


--
-- Name: user_role user_role_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_role
    ADD CONSTRAINT user_role_pkey PRIMARY KEY (id);


--
-- Name: user_role user_role_user_id_role_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_role
    ADD CONSTRAINT user_role_user_id_role_id_key UNIQUE (user_id, role_id);


--
-- Name: user_session user_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_session
    ADD CONSTRAINT user_session_pkey PRIMARY KEY (id);


--
-- Name: fnd_model_varient varient_uk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fnd_model_varient
    ADD CONSTRAINT varient_uk UNIQUE (model_id, code);


--
-- Name: app_inventory vehicle_uk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_inventory
    ADD CONSTRAINT vehicle_uk UNIQUE (product_no);


--
-- Name: inf_warehouse warehouse; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inf_warehouse
    ADD CONSTRAINT warehouse UNIQUE (code);


--
-- Name: idx_app_product_fuel_type_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_app_product_fuel_type_id ON public.app_product USING btree (fuel_type_id);


--
-- Name: idx_app_product_transmission_type_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_app_product_transmission_type_id ON public.app_product USING btree (transmission_type_id);


--
-- Name: idx_inventory_deleted_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_inventory_deleted_status ON public.app_inventory USING btree (deleted, status);


--
-- Name: idx_inventory_pod_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_inventory_pod_id ON public.app_inventory USING btree (purchase_order_detail_id);


--
-- Name: idx_jdetail_account; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_jdetail_account ON public.app_journal_detail USING btree (account_id);


--
-- Name: idx_jdetail_journal; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_jdetail_journal ON public.app_journal_detail USING btree (journal_id);


--
-- Name: idx_journal_date; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_journal_date ON public.app_journal USING btree (journal_date);


--
-- Name: idx_journal_reference; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_journal_reference ON public.app_journal USING btree (reference_type, reference_id);


--
-- Name: idx_payment_purchase_order_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_payment_purchase_order_id ON public.app_purchase_payment USING btree (purchase_order_id);


--
-- Name: idx_pod_product_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_pod_product_id ON public.app_purchase_order_detail USING btree (product_id);


--
-- Name: idx_pod_product_no_trgm; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_pod_product_no_trgm ON public.app_purchase_order_detail USING gin (lower((product_no)::text) public.gin_trgm_ops);


--
-- Name: idx_pod_purchase_order_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_pod_purchase_order_id ON public.app_purchase_order_detail USING btree (purchase_order_id);


--
-- Name: idx_pr_receipt_return; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_pr_receipt_return ON public.app_purchase_return_receipt USING btree (purchase_return_id);


--
-- Name: idx_product_brand_model_variant; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_product_brand_model_variant ON public.app_product USING btree (brand_id, model_id, varient_id);


--
-- Name: idx_purchase_deleted_order_date; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_purchase_deleted_order_date ON public.app_purchase_order USING btree (deleted, order_date DESC);


--
-- Name: idx_purchase_payment_account_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_purchase_payment_account_id ON public.app_purchase_payment USING btree (payment_account_id);


--
-- Name: idx_purchase_reference_no_trgm; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_purchase_reference_no_trgm ON public.app_purchase_order USING gin (lower((reference_no)::text) public.gin_trgm_ops);


--
-- Name: idx_purchase_return_inv; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_purchase_return_inv ON public.app_purchase_return USING btree (inventory_id);


--
-- Name: idx_revinfo_rev_timestamp; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_revinfo_rev_timestamp ON public.revinfo USING btree (rev_timestamp);


--
-- Name: idx_revinfo_user_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_revinfo_user_id ON public.revinfo USING btree (user_id);


--
-- Name: idx_sale_amount_split_sale_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_sale_amount_split_sale_id ON public.app_sale_amount_split USING btree (sale_id);


--
-- Name: idx_sale_refund_pay_return; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_sale_refund_pay_return ON public.app_sale_refund_payment USING btree (sale_return_id);


--
-- Name: idx_sale_return_date; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_sale_return_date ON public.app_sale_return USING btree (return_date);


--
-- Name: idx_sale_return_ded_return; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_sale_return_ded_return ON public.app_sale_return_deduction USING btree (sale_return_id);


--
-- Name: idx_sale_return_sale; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_sale_return_sale ON public.app_sale_return USING btree (sale_id);


--
-- Name: idx_transaction_account_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_transaction_account_id ON public.app_transaction USING btree (payment_account_id);


--
-- Name: idx_transaction_reference; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_transaction_reference ON public.app_transaction USING btree (reference_type, reference_id);


--
-- Name: idx_urt_session_active; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_urt_session_active ON public.user_refresh_token USING btree (session_id, revoked);


--
-- Name: idx_user_session_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_user_session_status ON public.user_session USING btree (session_id, status);


--
-- Name: idx_user_session_user_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_user_session_user_status ON public.user_session USING btree (user_id, status);


--
-- Name: idx_vendor_name_trgm; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_vendor_name_trgm ON public.app_vendor USING gin (lower((name)::text) public.gin_trgm_ops);


--
-- Name: ix_user_refresh_token_parent_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_user_refresh_token_parent_id ON public.user_refresh_token USING btree (parent_id);


--
-- Name: ix_user_refresh_token_user_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_user_refresh_token_user_id ON public.user_refresh_token USING btree (user_id);


--
-- Name: uq_coa_system_role; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX uq_coa_system_role ON public.fnd_chart_of_accounts USING btree (system_role) WHERE (system_role IS NOT NULL);


--
-- Name: ux_user_refresh_token_token_hash; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX ux_user_refresh_token_token_hash ON public.user_refresh_token USING btree (token_hash);


--
-- Name: app_inventory app_inventory_color_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_inventory
    ADD CONSTRAINT app_inventory_color_id_fkey FOREIGN KEY (color_id) REFERENCES public.fnd_lookup_master(id);


--
-- Name: app_payment_account app_payment_account_coa_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_payment_account
    ADD CONSTRAINT app_payment_account_coa_id_fkey FOREIGN KEY (coa_id) REFERENCES public.fnd_chart_of_accounts(id);


--
-- Name: app_product app_product_segment_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_product
    ADD CONSTRAINT app_product_segment_id_fkey FOREIGN KEY (segment_id) REFERENCES public.fnd_product_segment(id);


--
-- Name: app_purchase_payment app_purchase_payment_payment_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_purchase_payment
    ADD CONSTRAINT app_purchase_payment_payment_account_id_fkey FOREIGN KEY (payment_account_id) REFERENCES public.app_payment_account(id);


--
-- Name: app_purchase_payment app_purchase_payment_purchase_order_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_purchase_payment
    ADD CONSTRAINT app_purchase_payment_purchase_order_id_fkey FOREIGN KEY (purchase_order_id) REFERENCES public.app_purchase_order(id);


--
-- Name: app_purchase_return app_purchase_return_inventory_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_purchase_return
    ADD CONSTRAINT app_purchase_return_inventory_id_fkey FOREIGN KEY (inventory_id) REFERENCES public.app_inventory(id);


--
-- Name: app_purchase_return app_purchase_return_purchase_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_purchase_return
    ADD CONSTRAINT app_purchase_return_purchase_id_fkey FOREIGN KEY (purchase_id) REFERENCES public.app_purchase_order(id);


--
-- Name: app_purchase_return_receipt app_purchase_return_receipt_payment_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_purchase_return_receipt
    ADD CONSTRAINT app_purchase_return_receipt_payment_account_id_fkey FOREIGN KEY (payment_account_id) REFERENCES public.app_payment_account(id);


--
-- Name: app_purchase_return_receipt app_purchase_return_receipt_purchase_return_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_purchase_return_receipt
    ADD CONSTRAINT app_purchase_return_receipt_purchase_return_id_fkey FOREIGN KEY (purchase_return_id) REFERENCES public.app_purchase_return(id);


--
-- Name: app_sale_amount_split app_sale_amount_split_sale_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_sale_amount_split
    ADD CONSTRAINT app_sale_amount_split_sale_id_fkey FOREIGN KEY (sale_id) REFERENCES public.app_sale(id);


--
-- Name: app_sale_amount_split app_sale_amount_split_type_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_sale_amount_split
    ADD CONSTRAINT app_sale_amount_split_type_id_fkey FOREIGN KEY (type_id) REFERENCES public.fnd_lookup_master(id);


--
-- Name: app_sale_payment app_sale_payment_payment_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_sale_payment
    ADD CONSTRAINT app_sale_payment_payment_account_id_fkey FOREIGN KEY (payment_account_id) REFERENCES public.app_payment_account(id);


--
-- Name: app_sale_payment app_sale_payment_sale_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_sale_payment
    ADD CONSTRAINT app_sale_payment_sale_id_fkey FOREIGN KEY (sale_id) REFERENCES public.app_sale(id);


--
-- Name: app_sale_refund_payment app_sale_refund_payment_payment_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_sale_refund_payment
    ADD CONSTRAINT app_sale_refund_payment_payment_account_id_fkey FOREIGN KEY (payment_account_id) REFERENCES public.app_payment_account(id);


--
-- Name: app_sale_refund_payment app_sale_refund_payment_sale_return_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_sale_refund_payment
    ADD CONSTRAINT app_sale_refund_payment_sale_return_id_fkey FOREIGN KEY (sale_return_id) REFERENCES public.app_sale_return(id);


--
-- Name: app_sale_return_deduction app_sale_return_deduction_expense_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_sale_return_deduction
    ADD CONSTRAINT app_sale_return_deduction_expense_id_fkey FOREIGN KEY (expense_id) REFERENCES public.app_expense(id);


--
-- Name: app_sale_return_deduction app_sale_return_deduction_sale_return_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_sale_return_deduction
    ADD CONSTRAINT app_sale_return_deduction_sale_return_id_fkey FOREIGN KEY (sale_return_id) REFERENCES public.app_sale_return(id) ON DELETE CASCADE;


--
-- Name: app_sale_return app_sale_return_sale_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_sale_return
    ADD CONSTRAINT app_sale_return_sale_id_fkey FOREIGN KEY (sale_id) REFERENCES public.app_sale(id);


--
-- Name: app_transaction app_transaction_payment_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_transaction
    ADD CONSTRAINT app_transaction_payment_account_id_fkey FOREIGN KEY (payment_account_id) REFERENCES public.app_payment_account(id);


--
-- Name: app_transaction app_transaction_reversal_of_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_transaction
    ADD CONSTRAINT app_transaction_reversal_of_id_fkey FOREIGN KEY (reversal_of_id) REFERENCES public.app_transaction(id);


--
-- Name: fnd_brand_model brand_fk1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fnd_brand_model
    ADD CONSTRAINT brand_fk1 FOREIGN KEY (brand_id) REFERENCES public.fnd_product_brand(id);


--
-- Name: app_product brand_fk3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_product
    ADD CONSTRAINT brand_fk3 FOREIGN KEY (brand_id) REFERENCES public.fnd_product_brand(id) NOT VALID;


--
-- Name: fnd_product_brand category_fk1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fnd_product_brand
    ADD CONSTRAINT category_fk1 FOREIGN KEY (category_id) REFERENCES public.fnd_product_category(id);


--
-- Name: app_product category_fk3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_product
    ADD CONSTRAINT category_fk3 FOREIGN KEY (category_id) REFERENCES public.fnd_product_category(id) NOT VALID;


--
-- Name: app_vendor document_fk1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_vendor
    ADD CONSTRAINT document_fk1 FOREIGN KEY (document_id) REFERENCES public.app_document(id) NOT VALID;


--
-- Name: app_product document_fk3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_product
    ADD CONSTRAINT document_fk3 FOREIGN KEY (document_id) REFERENCES public.app_document(id) NOT VALID;


--
-- Name: app_inventory fk137ju93c22w2phcu3fqw2faa4; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_inventory
    ADD CONSTRAINT fk137ju93c22w2phcu3fqw2faa4 FOREIGN KEY (purchase_order_detail_id) REFERENCES public.app_purchase_order_detail(id);


--
-- Name: app_sale_aud fk17k4txn1s7rtp080yoaaf0aud; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_sale_aud
    ADD CONSTRAINT fk17k4txn1s7rtp080yoaaf0aud FOREIGN KEY (rev) REFERENCES public.revinfo(rev);


--
-- Name: app_direct_entry_aud fk63xpjm2yhd29gxcsfqyospi16; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_direct_entry_aud
    ADD CONSTRAINT fk63xpjm2yhd29gxcsfqyospi16 FOREIGN KEY (rev) REFERENCES public.revinfo(rev);


--
-- Name: app_purchase_order_aud fk7d5hxai2y1fexin3c369wb66; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_purchase_order_aud
    ADD CONSTRAINT fk7d5hxai2y1fexin3c369wb66 FOREIGN KEY (rev) REFERENCES public.revinfo(rev);


--
-- Name: app_purchase_return_aud fk7rh1f9yo9pr5kxsf0hkmypxh3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_purchase_return_aud
    ADD CONSTRAINT fk7rh1f9yo9pr5kxsf0hkmypxh3 FOREIGN KEY (rev) REFERENCES public.revinfo(rev);


--
-- Name: app_sale_return_aud fk9kxl5dwc7ikuh4wvpcr85hlb6; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_sale_return_aud
    ADD CONSTRAINT fk9kxl5dwc7ikuh4wvpcr85hlb6 FOREIGN KEY (rev) REFERENCES public.revinfo(rev);


--
-- Name: app_product fk_app_product_fuel_type; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_product
    ADD CONSTRAINT fk_app_product_fuel_type FOREIGN KEY (fuel_type_id) REFERENCES public.fnd_lookup_master(id);


--
-- Name: app_product fk_app_product_transmission_type; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_product
    ADD CONSTRAINT fk_app_product_transmission_type FOREIGN KEY (transmission_type_id) REFERENCES public.fnd_lookup_master(id);


--
-- Name: app_direct_entry fk_direct_entry_account; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_direct_entry
    ADD CONSTRAINT fk_direct_entry_account FOREIGN KEY (payment_account_id) REFERENCES public.app_payment_account(id);


--
-- Name: app_direct_entry fk_direct_entry_coa; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_direct_entry
    ADD CONSTRAINT fk_direct_entry_coa FOREIGN KEY (coa_id) REFERENCES public.fnd_chart_of_accounts(id) NOT VALID;


--
-- Name: app_expense fk_expense_payment_account; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_expense
    ADD CONSTRAINT fk_expense_payment_account FOREIGN KEY (payment_account_id) REFERENCES public.app_payment_account(id);


--
-- Name: app_journal_detail fk_jdetail_account; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_journal_detail
    ADD CONSTRAINT fk_jdetail_account FOREIGN KEY (account_id) REFERENCES public.fnd_chart_of_accounts(id);


--
-- Name: app_journal_detail fk_jdetail_journal; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_journal_detail
    ADD CONSTRAINT fk_jdetail_journal FOREIGN KEY (journal_id) REFERENCES public.app_journal(id);


--
-- Name: app_journal fk_journal_reversal; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_journal
    ADD CONSTRAINT fk_journal_reversal FOREIGN KEY (reversal_of_id) REFERENCES public.app_journal(id);


--
-- Name: app_expense_aud fkat6bvy56j7j5npo1p3jw8fkv6; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_expense_aud
    ADD CONSTRAINT fkat6bvy56j7j5npo1p3jw8fkv6 FOREIGN KEY (rev) REFERENCES public.revinfo(rev);


--
-- Name: app_expense fkba4r3qecjpry23hcupoclsvh; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_expense
    ADD CONSTRAINT fkba4r3qecjpry23hcupoclsvh FOREIGN KEY (expense_account_id) REFERENCES public.fnd_chart_of_accounts(id);


--
-- Name: fnd_product_segment fkbnkctr6eky2icq4q0wcf6i08b; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fnd_product_segment
    ADD CONSTRAINT fkbnkctr6eky2icq4q0wcf6i08b FOREIGN KEY (category_id) REFERENCES public.fnd_product_category(id);


--
-- Name: app_sale fkcbx21w4kb4hd366mv396bwu81; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_sale
    ADD CONSTRAINT fkcbx21w4kb4hd366mv396bwu81 FOREIGN KEY (customer_id) REFERENCES public.app_customer(id);


--
-- Name: app_purchase_payment_aud fkcfko6qau9krd4xm0pj3yyby37; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_purchase_payment_aud
    ADD CONSTRAINT fkcfko6qau9krd4xm0pj3yyby37 FOREIGN KEY (rev) REFERENCES public.revinfo(rev);


--
-- Name: app_sale_payment_aud fkd7r82kw40pp59b234ltv2nmil; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_sale_payment_aud
    ADD CONSTRAINT fkd7r82kw40pp59b234ltv2nmil FOREIGN KEY (rev) REFERENCES public.revinfo(rev);


--
-- Name: app_purchase_return_receipt_aud fkfo284ov6g747qvj4n8jjmwkpn; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_purchase_return_receipt_aud
    ADD CONSTRAINT fkfo284ov6g747qvj4n8jjmwkpn FOREIGN KEY (rev) REFERENCES public.revinfo(rev);


--
-- Name: app_sale fkgx1ea9fp6pvboi1cn4ikrggvy; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_sale
    ADD CONSTRAINT fkgx1ea9fp6pvboi1cn4ikrggvy FOREIGN KEY (inventory_id) REFERENCES public.app_inventory(id);


--
-- Name: app_inventory fkhbn2ih1i7ele8pv6epthq9okd; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_inventory
    ADD CONSTRAINT fkhbn2ih1i7ele8pv6epthq9okd FOREIGN KEY (product_id) REFERENCES public.app_product(id);


--
-- Name: app_sale fkjxulhkw1t2wm0oa15x6mdlqvc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_sale
    ADD CONSTRAINT fkjxulhkw1t2wm0oa15x6mdlqvc FOREIGN KEY (status_id) REFERENCES public.fnd_lookup_master(id);


--
-- Name: app_sale_return_deduction_aud fknlgs0obdmqh7pd3x9mwyas54v; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_sale_return_deduction_aud
    ADD CONSTRAINT fknlgs0obdmqh7pd3x9mwyas54v FOREIGN KEY (rev) REFERENCES public.revinfo(rev);


--
-- Name: app_sale_refund_payment_aud fksqumbarfxa4fn418up5p8vw7f; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_sale_refund_payment_aud
    ADD CONSTRAINT fksqumbarfxa4fn418up5p8vw7f FOREIGN KEY (rev) REFERENCES public.revinfo(rev);


--
-- Name: fnd_lookup_master fnd_lookup_master_offset_coa_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fnd_lookup_master
    ADD CONSTRAINT fnd_lookup_master_offset_coa_id_fkey FOREIGN KEY (offset_coa_id) REFERENCES public.fnd_chart_of_accounts(id);


--
-- Name: fnd_resource fnd_resource_module_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fnd_resource
    ADD CONSTRAINT fnd_resource_module_id_fkey FOREIGN KEY (module_id) REFERENCES public.fnd_module(id);


--
-- Name: fnd_role_privilege fnd_role_privilege_resource_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fnd_role_privilege
    ADD CONSTRAINT fnd_role_privilege_resource_id_fkey FOREIGN KEY (resource_id) REFERENCES public.fnd_resource(id);


--
-- Name: fnd_role_privilege fnd_role_privilege_role_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fnd_role_privilege
    ADD CONSTRAINT fnd_role_privilege_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.fnd_role(id);


--
-- Name: fnd_model_varient model_fk1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fnd_model_varient
    ADD CONSTRAINT model_fk1 FOREIGN KEY (model_id) REFERENCES public.fnd_brand_model(id);


--
-- Name: app_product model_fk3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_product
    ADD CONSTRAINT model_fk3 FOREIGN KEY (model_id) REFERENCES public.fnd_brand_model(id) NOT VALID;


--
-- Name: app_purchase_order_detail product_fk4; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_purchase_order_detail
    ADD CONSTRAINT product_fk4 FOREIGN KEY (product_id) REFERENCES public.app_product(id);


--
-- Name: user_profile profile_photo_fk1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_profile
    ADD CONSTRAINT profile_photo_fk1 FOREIGN KEY (profile_photo_id) REFERENCES public.app_document(id) NOT VALID;


--
-- Name: app_purchase_order_detail purchase_order_fk1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_purchase_order_detail
    ADD CONSTRAINT purchase_order_fk1 FOREIGN KEY (purchase_order_id) REFERENCES public.app_purchase_order(id);


--
-- Name: app_expense purchase_order_fk3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_expense
    ADD CONSTRAINT purchase_order_fk3 FOREIGN KEY (purchase_order_id) REFERENCES public.app_purchase_order(id);


--
-- Name: app_purchase_order status_fk2; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_purchase_order
    ADD CONSTRAINT status_fk2 FOREIGN KEY (status_id) REFERENCES public.fnd_lookup_master(id);


--
-- Name: user_refresh_token user_refresh_token_parent_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_refresh_token
    ADD CONSTRAINT user_refresh_token_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.user_refresh_token(id);


--
-- Name: user_refresh_token user_refresh_token_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_refresh_token
    ADD CONSTRAINT user_refresh_token_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profile(id);


--
-- Name: user_role user_role_role_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_role
    ADD CONSTRAINT user_role_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.fnd_role(id);


--
-- Name: user_role user_role_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_role
    ADD CONSTRAINT user_role_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profile(id);


--
-- Name: app_product varient_fk1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_product
    ADD CONSTRAINT varient_fk1 FOREIGN KEY (varient_id) REFERENCES public.fnd_model_varient(id) NOT VALID;


--
-- Name: app_purchase_order vendor_fk1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_purchase_order
    ADD CONSTRAINT vendor_fk1 FOREIGN KEY (vendor_id) REFERENCES public.app_vendor(id);


-- Completed on 2026-07-19 13:53:01 IST

--
-- PostgreSQL database dump complete
--

