package com.triasoft.garage.constants;

public enum StatusEnum {
    ACTIVE, INACTIVE, DELETED,
    AVAILABLE, OUT_OF_STOCK, PENDING_DELIVERY, RETURNED_TO_VENDOR,
    PENDING, RECIEVED, SOLD, CANCELLED, COMPLETED, PAID, PARTIAL, FINANCE_PENDING, REFUND, RETURNED
}
